#!/usr/bin/env bash

# Hook to make sure that no commit message line exceeds 72 characters

while read line; do
    # Skip comments
    if [ "${line:0:1}" == "#" ]; then
        continue
    fi
    if [ ${#line} -le 10 ]; then
        echo "Commit message must be >10 characters!"
        echo "The following commit message has ${#line} characters."
        echo "${line}"
        exit 1;
    fi
done < "${1}"

exit 0;
